#!/bin/bash

# get seconds since epoch
test "x$1" == x && date +%s && exit 0

# or convert epoch seconds to date format (see "man date" for options)
EPOCH="$1"
shift
if [ $EPOCH -gt 9999999999 ] ; then
     date -d @$(($EPOCH/1000)) "$@" "+%F %T %Z"
else
     date -d @"$EPOCH" "$@" "+%F %T %Z"
fi
